AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.name }} lambda stack using `holy-lambda` micro library

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
  Entrypoint:
    Type: String
    Default: "{{ cookiecutter.name }}.core"

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        HL_ENTRYPOINT: !Ref Entrypoint

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ExampleLambdaFunction
      PackageType: Image
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /
            Method: GET
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

  ExampleHttpApi:
    Type: AWS::Serverless::HttpApi

Outputs:
  ExampleLambdaEndpoint:
    Description: Endpoint for ExampleLambdaFunction
    Value:
      Fn::Sub: https://${ExampleHttpApi}.execute-api.${AWS::Region}.amazonaws.com
